Once Again

diff --git a/.github/workflows/build-design-tokens.yml b/.github/workflows/build-design-tokens.yml
--- a/.github/workflows/build-design-tokens.yml
+++ b/.github/workflows/build-design-tokens.yml
@@ -36,3 +36,36 @@ jobs:
       run: git push origin main
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  
+  chromatic_publish:
+    runs-on: ubuntu-latest
+    needs: build_tokens
+
+    steps:
+      # Check if the push to main has completed successfully
+      - name: Check if push is successful
+        run: |
+          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
+            echo "Push to main branch is successful. Proceed with Chromatic Publish."
+          else
+            echo "Push to main branch failed. Exiting Chromatic Publish."
+            exit 1
+          fi
+
+      # Steps for Chromatic Publish
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+
+      - run: npm install
+        working-directory: ./design-system
+
+      - uses: chromaui/action@v1
+        with:
+          workingDir: ./design-system
+          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
+          token: ${{ secrets.GITHUB_TOKEN }}
